version: "3.4"

services:
  lucky-draw:
    container_name: lucky_draw
    build:
      context: ./lucky-draw
    ports:
      - 8000:8000
    volumes:
      - ./lucky-draw:/app
      - /app/node_modules

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
      - ./prometheus/data:/prometheus/data
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/config.yml"

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - ./lucky-draw/logs:/logs
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
